# Generated by Selenium IDE
import pytest
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class SeleniumWeekFour(unittest.TestCase):
  def setUp(self) -> None:
        self.driver = webdriver.Chrome()

  def tearDown(self) -> None:
      if self.driver:
          self.driver.quit()
  
  def test_headerTest(self):
    print("\nRunning 'Header' test.\n")

    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.implicitly_wait(5)
    self.driver.maximize_window()

    self.driver.find_element(By.CSS_SELECTOR, ".css-1f91msi > .css-mcpu91").click()
    self.driver.find_element(By.ID, "popover-trigger-:r2:").click()
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .chakra-stack .chakra-text").click()
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) .chakra-text").click()
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) .chakra-text").click()
    self.driver.find_element(By.ID, "popover-trigger-:r6:").click()
    try:
       self.driver.find_element(By.CSS_SELECTOR, ".css-ankmtx").click()
    except:
       self.driver.find_element(By.CSS_SELECTOR, ".css-16h2qf1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1f91msi > .css-mcpu91").click()
    self.driver.find_element(By.ID, "popover-trigger-:r2:").click()
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .chakra-stack .chakra-text").click()
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) .chakra-text").click()
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) .chakra-text").click()
    self.driver.find_element(By.ID, "popover-trigger-:r6:").click()
    time.sleep(5)

  def test_footerSitemapTest(self):
    print("\nRunning 'Footer - SiteMap' test.\n")

    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.implicitly_wait(5)
    self.driver.maximize_window()

    self.driver.find_element(By.LINK_TEXT, "Penelitian").click()
    self.driver.find_element(By.LINK_TEXT, "Data/Wawancara").click()
    self.driver.find_element(By.LINK_TEXT, "PKL/Magang/KKN").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6)").click()
    try:
       self.driver.find_element(By.CSS_SELECTOR, ".css-ankmtx").click()
    except:
       self.driver.find_element(By.CSS_SELECTOR, ".css-16h2qf1").click()
    self.driver.find_element(By.LINK_TEXT, "Penelitian").click()
    self.driver.find_element(By.LINK_TEXT, "Data/Wawancara").click()
    self.driver.find_element(By.LINK_TEXT, "PKL/Magang/KKN").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6)").click()
    time.sleep(5)

  def test_footerContactUsTest(self):
    print("\nRunning 'Footer - Contact Us' test.\n")

    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.implicitly_wait(5)
    self.driver.maximize_window()

    self.driver.find_element(By.XPATH, '//*[@id="root"]/div/div[7]/div/div/div[3]/a[1]/button').click()
    self.driver.switch_to.window(self.driver.window_handles[0])
    
    self.driver.find_element(By.XPATH, '//*[@id="root"]/div/div[7]/div/div/div[3]/a[2]/button').click()
    self.driver.switch_to.window(self.driver.window_handles[0])
    
    self.driver.find_element(By.XPATH, '//*[@id="root"]/div/div[7]/div/div/div[3]/div/a[1]').click()

    self.driver.execute_script("window.open('', '_blank');")
    self.driver.switch_to.window(self.driver.window_handles[-1])
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.find_element(By.XPATH, '//*[@id="root"]/div/div[7]/div/div/div[3]/div/a[2]').click()
    
    self.driver.execute_script("window.open('', '_blank');")
    self.driver.switch_to.window(self.driver.window_handles[-1])
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.find_element(By.XPATH, '//*[@id="root"]/div/div[7]/div/div/div[3]/div/a[3]').click()
    time.sleep(5)

  def test_pelayananPenelitianForm(self):
    print("\nRunning 'Pelayanan Form - Penelitian' test.\n")

    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.implicitly_wait(5)
    self.driver.maximize_window()

    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .chakra-stack .chakra-text").click()
    
    self.driver.find_element(By.ID, "nama").send_keys("abc")
    self.driver.find_element(By.ID, "alamat").send_keys("abc")
    self.driver.find_element(By.ID, "no_identitas").send_keys("abc")
    self.driver.find_element(By.ID, "tujuan_dinas").send_keys("abc")
    self.driver.find_element(By.ID, "anggota").send_keys("abc")
    self.driver.find_element(By.ID, "nama_kampus").send_keys("abc")
    self.driver.find_element(By.ID, "no_surat_kampus").send_keys("abc")
    self.driver.find_element(By.ID, "tanggal_surat_kampus").send_keys("9999-09-09")
    self.driver.find_element(By.ID, "judul_penelitian").send_keys("abc")
    self.driver.find_element(By.ID, "no_hp").send_keys("abc")

    file_path = r"C:\\Users\\muham\\OneDrive\\Pictures\\hqdefault.jpg"

    self.driver.find_element(By.ID, "attach_ktp").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_ktm").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_pasFoto").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_notaris").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_suratKampus").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_vaksin").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_proposal").send_keys(file_path)
    
    self.driver.find_element(By.ID, "tombolKirim").click()
    time.sleep(5)

  def test_pelayananDataForm(self):
    print("\nRunning 'Pelayanan Form - Data Wawancara Observasi' test.\n")

    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.implicitly_wait(5)
    self.driver.maximize_window()

    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > .chakra-stack .chakra-text").click()
    
    self.driver.find_element(By.ID, "nama").send_keys("abc")
    self.driver.find_element(By.ID, "alamat").send_keys("abc")
    self.driver.find_element(By.ID, "no_identitas").send_keys("abc")
    self.driver.find_element(By.ID, "tujuan_dinas").send_keys("abc")
    self.driver.find_element(By.ID, "judul_data").send_keys("abc")
    self.driver.find_element(By.ID, "anggota").send_keys("abc")
    self.driver.find_element(By.ID, "nama_kampus").send_keys("abc")
    self.driver.find_element(By.ID, "no_surat_kampus").send_keys("abc")
    self.driver.find_element(By.ID, "tanggal_surat_kampus").send_keys("9999-09-09")
    self.driver.find_element(By.ID, "no_hp").send_keys("abc")

    file_path = r"C:\\Users\\muham\\OneDrive\\Pictures\\hqdefault.jpg"

    self.driver.find_element(By.ID, "attach_ktp").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_ktm").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_pasFoto").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_suratKampus").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_vaksin").send_keys(file_path)

    self.driver.find_element(By.ID, "tombolKirim").click()
    time.sleep(5)

  def test_pelayananPKLForm(self):
    print("\nRunning 'Pelayanan Form - PKL Magang KKN Pengabdian Masyarakat' test.\n")

    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.implicitly_wait(5)
    self.driver.maximize_window()

    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) > .chakra-stack .chakra-text").click()
    
    self.driver.find_element(By.ID, "nama").send_keys("abc")
    self.driver.find_element(By.ID, "alamat").send_keys("abc")
    self.driver.find_element(By.ID, "no_identitas").send_keys("abc")
    self.driver.find_element(By.ID, "anggota").send_keys("abc")
    self.driver.find_element(By.ID, "nama_kampus").send_keys("abc")
    self.driver.find_element(By.ID, "no_surat_kampus").send_keys("abc")
    self.driver.find_element(By.ID, "tanggal_surat_kampus").send_keys("9999-09-09")
    self.driver.find_element(By.ID, "no_hp").send_keys("abc")
    self.driver.find_element(By.ID, "nama_dinas_terkait").send_keys("abc")
    self.driver.find_element(By.ID, "no_surat_dinas").send_keys("abc")
    self.driver.find_element(By.ID, "tanggal_surat_dinas").send_keys("9999-09-09")
    self.driver.find_element(By.ID, "tanggal_mulai").send_keys("9999-09-09")
    self.driver.find_element(By.ID, "tanggal_akhir").send_keys("9999-09-09")
    self.driver.find_element(By.ID, "no_surat_dinas").send_keys("abc")

    file_path = r"C:\\Users\\muham\\OneDrive\\Pictures\\hqdefault.jpg"

    self.driver.find_element(By.ID, "attach_ktp").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_ktm").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_pasFoto").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_suratKampus").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_vaksin").send_keys(file_path)
    self.driver.find_element(By.ID, "attach_suratDinas").send_keys(file_path)

    self.driver.find_element(By.ID, "tombolKirim").click()
    time.sleep(5)
    
if __name__ == '__main__':
  unittest.main()